#!/bin/sh
#
# scrub-md-devivces scrub linux md devices periodically

# This script will scrub linux md devices as per
# https://raid.wiki.kernel.org/index.php/Scrubbing_the_drives
# (see the notes on raid6 there if you use it)
#
# Run periodically, eg. from cron.
#
# https://github.com/jnorell/scrub-md-devices

# Copyright (c) 2018, Jesse Norell <jesse@kci.net>
# Copyright (c) 2018, Kentec Communications, Inc.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.


# todo:  for raid6, any data errors should be follwed with running 'raid6check'


ls -1d /sys/block/md*/md 2>/dev/null | while read md
do
	if [ -f "${md}/level" -a -f "${md}/sync_action" -a "`cat ${md}/sync_action`" = "idle" ]
	then
		if [ "`cat ${md}/level`" = "raid5" ]
		then
			echo repair > "${md}/sync_action"
		else
			echo check > "${md}/sync_action"
		fi
	fi
done

exit 0
